name: Pandora CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - name: Build and test release
        env:
          CMAKE_BUILD_TYPE: RELEASE
        run:
          ls
          pwd
          bash ci/script.sh
