name: Pandora CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install cmake
      - name: Check out code for the build
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build and test
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DHUNTER_JOBS_NUMBER=4 ..
          make -j4
          ctest -vv
          ./pandora --help